apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: namegen-ingress
  namespace: namegen
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: namegen.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: namegen-api
                port:
                  number: 80